spring:
  config:
    activate:
      on-profile: local

redis:
  host: localhost
  port: 6379

feign:
  client:
    url:
      game-service: http://localhost:8081

---

spring:
  config:
    activate:
      on-profile: dev

redis:
  host: ${REDIS_HOST}
  port: 6379

feign:
  client:
    url:
      game-service: http://dev-game-service:8080