spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

management:
  endpoints:
    web:
      exposure:
        include: health, info
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8085
---
spring:
  config:
    activate:
      on-profile: dev
