server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health, info
springdoc:
  swagger-ui:
    use-root-path: true
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://k8s-apps-devgatew-4d7f7a82e4-1838977854.ap-northeast-2.elb.amazonaws.com"
              - "http://localhost:8080"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://localhost:8081
          predicates:
            - Path=/game/**
          filters:
            - StripPrefix=1
springdoc:
  swagger-ui:
    urls[0]:
      name: Game API
      url: http://localhost:8080/game/api-docs
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://dev-quiz-service:8080
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=1
        - id: game
          uri: http://dev-game-service:8080
          predicates:
              - Path=/game/**
          filters:
              - StripPrefix=1
        - id: user
          uri: http://dev-user-service:8080
          predicates:
              - Path=/user/**
          filters:
              - StripPrefix=1
        - id: matching
          uri: http://dev-matching-service:8080
          predicates:
              - Path=/matching/**
          filters:
              - StripPrefix=1
        - id: search
          uri: http://dev-search-service:8080
          predicates:
              - Path=/search/**
          filters:
              - StripPrefix=1
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        primary-port-name: http
logging:
  level:
    org.springframework.cloud.gateway: DEBUG

springdoc:
  swagger-ui:
    urls[0]:
      name: Game API
      url: http://${GATEWAY_HOST}/game/api-docs
    urls[1]:
      name: Quiz API
      url: http://${GATEWAY_HOST}/quiz/api-docs
    urls[2]:
      name: Matching API
      url: http://${GATEWAY_HOST}/matching/api-docs
    urls[3]:
      name: Search API
      url: http://${GATEWAY_HOST}/search/api-docs
    urls[4]:
      name: User API
      url: http://${GATEWAY_HOST}/user/api-docs