server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health, gateway, info
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://localhost:8081
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=1
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://dev-quiz-service:8080
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=1
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        primary-port-name: http
logging:
  level:
    org.springframework.cloud.gateway: DEBUG