server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health, info
---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://localhost:8081
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=1
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://dev-quiz-service:8080
          predicates:
            - Path=/quiz/**
          filters:
            - StripPrefix=1
        - id: game
          uri: http://dev-game-service:8080
          predicates:
              - Path=/game/**
          filters:
              - StripPrefix=1
        - id: user
          uri: http://dev-user-service:8080
          predicates:
              - Path=/user/**
          filters:
              - StripPrefix=1
        - id: matching
          uri: http://dev-matching-service:8080
          predicates:
              - Path=/matching/**
          filters:
              - StripPrefix=1
        - id: search
          uri: http://dev-search-service:8080
          predicates:
              - Path=/search/**
          filters:
              - StripPrefix=1
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        primary-port-name: http
logging:
  level:
    org.springframework.cloud.gateway: DEBUG