server:
  shutdown: graceful
management:
  endpoints:
    web:
      exposure:
        include: health, info
springdoc:
  swagger-ui:
    use-root-path: true
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: false

---
spring:
  config:
    activate:
      on-profile: local
  cloud:
    gateway:
      routes:
        - id: game
          uri: http://localhost:8081
          predicates:
            - Path=/api/game/**
        - id: matching
          uri: http://localhost:8082
          predicates:
            - Path=/api/matching/**
        - id: quiz
          uri: http://localhost:8083
          predicates:
            - Path=/api/quiz/**
        - id: user
          uri: http://localhost:8085
          predicates:
            - Path=/api/user/**
        - id: oauth2
          uri: http://localhost:8085
          predicates:
            - Path=/oauth2/**
        - id: websocket
          uri: ws://localhost:8081
          predicates:
            - Path=/ws/**
        - id: sockjs
          uri: http://localhost:8081
          predicates:
            - Path=/ws/**
            - Query=transport, websocket
  data:
    redis:
      host: localhost
      port: 6379

springdoc:
  swagger-ui:
    urls[0]:
      name: Quiz API
      url: http://localhost:8080/api/quiz/api-docs

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일

logging:
  level:
    org:
      springframework:
        DEBUG
---
spring:
  config:
    activate:
      on-profile: dev
  cloud:
    gateway:
      routes:
        - id: quiz
          uri: http://dev-quiz-service:8080
          predicates:
            - Path=/api/quiz/**
        - id: game
          uri: http://dev-game-service:8080
          predicates:
            - Path=/api/game/**
        - id: user
          uri: http://dev-user-service:8080
          predicates:
              - Path=/api/user/**
        - id: matching
          uri: http://dev-matching-service:8080
          predicates:
            - Path=/api/matching/**

    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
        primary-port-name: http


redis:
  host: ${REDIS_HOST}
  port: 6379

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    root: DEBUG

springdoc:
  swagger-ui:
    urls[0]:
      name: Game API
      url: http://${GATEWAY_HOST}/api/game/api-docs
    urls[1]:
      name: Quiz API
      url: http://${GATEWAY_HOST}/api/quiz/api-docs
    urls[2]:
      name: Matching API
      url: http://${GATEWAY_HOST}/api/matching/api-docs
    urls[3]:
      name: User API
      url: http://${GATEWAY_HOST}/api/user/api-docs

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 3600000  # 1시간
  refresh-token-validity: 604800000  # 7일

