spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

server:
  tomcat:
    max-connections: 10000
    accept-count: 1000
    connection-timeout: 20000
    threads:
      max: 200

management:
  endpoints:
    web:
      exposure:
        include: health, info, openapi, swagger-ui
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8083

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: api/quiz/api-docs
  enable-spring-security: true
---
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: api/quiz/api-docs
  enable-spring-security: true