management:
  endpoints:
    web:
      exposure:
        include: health
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8081
---
spring:
  config:
    activate:
      on-profile: dev
