spring:
  profiles:
    group:
      local: common, domain, infra
      dev: common, domain, infra

management:
  endpoints:
    web:
      exposure:
        include: health, info, openapi, swagger-ui
---
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8084
---
spring:
  config:
    activate:
      on-profile: dev
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api-docs
  enable-spring-security: true
