name: Gateway Image Build

env:
  BUILD_ID: ${{ github.sha }}-${{ github.run_id }}
  HELM_VALUE: gateway-service-chart/values-dev.yaml
  HELM_BRANCH: dev

on:
  push:
    paths:
      - 'gateway-service/**'
  pull_request:
    paths:
      - 'gateway-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials for China region audience
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: quizy
          IMAGE_TAG: ${{ env.BUILD_ID }}
        run: |
          docker build -f ./gateway-service/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
      - name: Checkout Helm Repository
        uses: actions/checkout@v4
        with:
          repository: quizy-web/quizy-helm-charts
          path: helm-chart
          ref: dev
          ssh-key: ${{ secrets.HELM_REPO_SSH_KEY }}
      - name: Change Image tag of the Helm Chart
        uses: mikefarah/yq@v4.34.1
        with:
          cmd: yq -i '.image.tag = "${{ env.BUILD_ID }}"' helm-chart/${{ env.HELM_VALUE }}

      - name: Commit an Push the Helm Chart
        run: |
          cd helm-chart
          git config --local user.email "githubaction@gmail.com"
          git config --local user.name "githubaction"
          git add ${{ env.HELM_VALUE }}
          git commit -m "Commit HELM changes ${{ env.ECR_REPOSITORY }}:${{ env.BUILD_ID }}"
          current_branch=$(git branch --show-current)
          git checkout -b ${{ env.HELM_BRANCH }} && git merge ${current_branch}
          git push --force origin ${{ env.HELM_BRANCH }}
